### ISSUE TITLE
document_page_adhoc conflicting with OCA/knowledge/document_page

### ISSUE THREAD

**Issue by ivantodorovich** [jjscarafia/odoo-help#2]
I know this might not concern you, but `document_page_adhoc` defines a model named `document.page`, which conflicts with OCA's `document_page` module.

I've noticed your `document_page_adhoc` is very similar to OCA's, but somewhat outdated (OCA is written in the new api)

Haven't looked that hard into your code, but it might be possible to just remove that module entirely and use OCA's instead... for the sake of modules compatibilities.

**Comment by jjscarafia** [comment]
Hi Ivan, thanks for your contact. The think is that to depreceate this module I need to change from this one to the OCA one for all of our customers. 
I will check it and try to make it. For sure we are not going to use this module on version 9.

Why this module bothers? They have differnt names, so at least you install no issue for you.

We are looking forward to depreceate all this repository, but it will take some months. So, let me know if no problem to wait a few months

**Comment by ivantodorovich** [comment]
Even though they have different module names, they both define
'document.page' model.

The one from OCA inherits mail.thread (or however it's called - I'm
answering from the phone right now) and most modules requiring
document_page (for instance, OCA/management-system) throw an error on
install because of the missing follower_messages_ids field (again, or
however it's called).

To work around it I had to uninstall this module entirely and use OCA's
instead. It's not biggie, though, this module isn't really indispensable,
but I thought you might want to be aware of the issue.

**Comment by jjscarafia** [comment]
Thanks for the response. Give a few weeks and I will remove it. We are not
using this documentation modules anymore.
Thanks!

**Comment by ivantodorovich** [comment]
No problem :+1:

Thank you, really.
